---
title: "X-means"
author: "Erick Calderon-Morales"
date: "7/1/2021"
output: html_document
---

```{r}
#install.packages("clusternor",dependencies = T)
library("clusternor")
install.packages("knor")
```

```{r}
data(test_data)
test_data
```

```{r}
iris.mat <- as.matrix(iris[,1:4])

# Number of unique classes
kmax <- 2
xms_2 <- Xmeans(iris.mat, kmax)
xms_2
```



```{r}



iris.mat <- as.matrix(iris[,1:4])

# Number of unique classes
kmax <- 1
xms_10 <- Xmeans(iris.mat, kmax)
xms_10


```

```{r}
library("tidyverse")
library("janitor")
data_rgr_agr <- 
  read.csv("~/Documents/projects/shade_house_experiment/data/finalDat.csv", 
  		 header = T) %>%
	clean_names() 


data_rgr_agr$treatment <- factor(data_rgr_agr$treatment,
					levels = c(
							   "ambientrain", 
							   "ambientrain_nutrients",
							   "ambientrain_water",
							   "ambientrain_water_nutrients"
							   )
					)

#Clean data
data_agr_clean <- 
    data_rgr_agr %>% 
	# Convert to factor nfixer
	mutate(nfixer = factor(nfixer)) %>% 
    
    # Order the columns  
    dplyr::select(id,spcode,family,treatment,nfixer,init_height,agr)
  
```



```{r}
library("mlr3cluster")
library(mlr3)
library(mlr3cluster)
library("mlr3verse")


as.data.table(mlr_tasks)
task = mlr_tasks$get("penguins")

train_set = sample(task$nrow, 0.8 * task$nrow)
test_set = setdiff(seq_len(task$nrow), train_set)

learner = mlr_learners$get("clust.kmeans")
learner$train(task, row_ids = train_set)

preds = learner$predict(task, row_ids = test_set)
preds


```

```{r}
library(mlr3viz)

task = mlr_tasks$get("penguins")
learner = mlr_learners$get("clust.kmeans")
learner$param_set$values = list(centers = 3L)
learner$train(task)
    

preds = learner$predict(task)

# Task visualization
autoplot(task)
```



```{r}
task = mlr_tasks$get("usarrests")
train_set = sample(task$nrow, 0.8 * task$nrow)
test_set = setdiff(seq_len(task$nrow), train_set)

learner = mlr_learners$get("clust.kmeans")
learner$train(task, row_ids = train_set)

preds = learner$predict(task, row_ids = test_set)
preds
```

```{r}
library(RWeka)

WPM("install-package", "XMeans")
WPM("refresh-cache") # Build Weka package metadata cache


data("iris")

cl1 <- SimpleKMeans(iris[, -5], Weka_control(N = 3))
table(predict(cl1), iris$Species)

cl2 <- XMeans(iris[, -5],c("-L", 3, "-H", 7, "-use-kdtree",
                           "-K","weka.core.neighboursearch.KDTree-P"))

x_means <- XMeans(iris[,1:4], control = weka_ctrl)

table(predict(cl2), iris$Species)
```

